export const ProfileEvents = {
  userLoggedIn: 'profileUserLoggedIn',
  userNotAuth: 'profileUserNotAuth',
  userDataUpdateSuccess: 'userDataUpdateSuccess',
  userDataUpdateFailed: 'userDataUpdateFailed',
  userOrderHistoryGetSuccess: 'userOrderHistoryGetSuccess',
  userOrderHistoryGetFailed: 'userOrderHistoryGetFailed',
  userReviewPublishSuccess: 'userReviewPublishSuccess',
  userOrderCreatedSuccess: 'userOrderCreatedSuccess',
  userOrderGetSuccess: 'userOrderGetSuccess',
  userOrderGetFailed: 'userOrderGetFailed',
  userFavouriteSwitchSuccess: 'userFavouriteSwitchSuccess',
  userFavouriteSwitchFailed: 'userFavouriteSwitchFailed',
  userFavouriteRestaurantsGetSuccess: 'userFavouriteRestaurantsGetSuccess',
  userOrderGetSuccessForStatus: 'userOrderGetSuccessForStatus',
};
