name: Build and Delivery

on:
  push:
    branches:
      - GM-44_Order_Status

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v2

      - name:  Install deps
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Copy SW
        run: cp src/sw.js dist/ && cp src/fav.png dist/ && cp src/favincon.ico dist/ && cp src/manifest.json dist/


      - name: Upload build result
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Transfer build files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          source: "dist/*"
          target: ${{ secrets.DIST_PATH }}